name: PHP CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # Step 3: Check PHP syntax
      - name: PHP Syntax Check
        run: find . -name "*.php" -print0 | xargs -0 -n1 php -l

      # Step 4: Display PHP version
      - name: Show PHP Version
        run: php -v
